### ISSUE TITLE
exception when add fieldtype in yaml

### ISSUE THREAD

**Issue by m49n** [GinoPane/oc-awesomeiconslist-plugin#2]
The partial '_field_awesomeiconslist,.htm' is not found.

**Comment by m49n** [comment]
Its wrong for yaml

awesome_icon:
label: Icon,
type: awesomeiconslist,
unicodeValue: false,
emptyOption: false,
iconTypes: brands,
placeholder: Select Icon,
span: left

Just delete "," and its work
awesome_icon:
label: Icon
type: awesomeiconslist
unicodeValue: false
emptyOption: false
iconTypes: brands
placeholder: Select Icon
span: left

**Comment by faselunare** [comment]
Hi, this is my yml... but it doesn't works
```
 urls:
            label: 'Links & social'
            prompt: 'Add new item'
            span: right
            type: repeater
            maxItems: 4
            tab: Organizer
            form:
                fields:
                    service:
                        label: 'Service (Facebook, Instagram, Website ...)'
                        span: left
                        placeholder: Facebook
                        type: text
                    link:
                        label: Url
                        span: right
                        placeholder: 'https://'
                        type: text
                    awesome_icon:
                        label: Icon,
                        type: awesomeiconslist,
                        unicodeValue: false,
                        emptyOption: false,
                        iconTypes: brands,
                        placeholder: Select Icon
```
i always get
The partial '_field_awesomeiconslist,.htm' is not found.

this code where should it be inserted? 
```
$form->addFields([
    'awesome_icon' => [
        'label'         => 'Icon',
        'type'          => 'awesomeiconslist',
        'unicodeValue'  => false,
        'emptyOption'   => false,
        'iconTypes'     => 'solid, regular',
        'placeholder'   => "Select Icon",
        'span'          => 'left'
    ]
]);
```

**Comment by GinoPane** [comment]
Wow. I have no idea why I haven't seen this opened before 😄 

@faselunare I have an error in README, yaml config should bot contain commas, so the correct config for you will be:

```
urls:
            label: 'Links & social'
            prompt: 'Add new item'
            span: right
            type: repeater
            maxItems: 4
            tab: Organizer
            form:
                fields:
                    service:
                        label: 'Service (Facebook, Instagram, Website ...)'
                        span: left
                        placeholder: Facebook
                        type: text
                    link:
                        label: Url
                        span: right
                        placeholder: 'https://'
                        type: text
                    awesome_icon:
                        label: Icon
                        type: awesomeiconslist
                        unicodeValue: false
                        emptyOption: false
                        iconTypes: brands
                        placeholder: Select Icon
```

The field usage with code can be done when you inject fields into forms for plugins. For example, this is its usage from another plugin: https://github.com/GinoPane/oc-awesomecategories-plugin/blob/c475ff41324ff9e35d9049a35e7bbc86ead77762/Plugin.php#L114
